swagger: '2.0'
info:
  description: This is the Documentation of the Shop Prototype.
  version: 1.0.0
  title: api.shop.com - The example
  contact:
    email: info@shop.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:3000'
basePath: /
tags:
  - name: customer
    description: A customer of the shop
schemes:
  - http
paths:
  '/customer':
    post:
      tags:
        - customer
      summary: Add a new customer to the shop
      description: ''
      operationId: customerService.create
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: customer object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/customer'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/customer'
        '400':
          description: Invalid Content - Expects 'application/json'
        '409':
          description: Invalid Argument - The given ZIP Code is not in the delivery area!
        '500':
          description: Internal Error
  '/customer/{customerId}':
    get:
      tags:
        - customer
      summary: Find customer by ID
      description: Returns a single customer
      operationId: customerService.getById
      produces:
        - application/json
      parameters:
        - name: customerId
          in: path
          description: ID of customer to return
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/customer'
        '400':
          description: Invalid Content - Expects 'application/json'
        '404':
          description: Customer not found
    put:
      tags:
        - customer
      summary: Updates a customer in the store with form data
      description: ''
      operationId: customerService.update
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: customerId
          in: path
          description: ID of customer that needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: customer object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/customer'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/customer'
        '400':
          description: Invalid Content - Expects 'application/json'
        '404':
          description: Customer not Found
        '409':
          description: Invalid Argument - The given ZIP Code is not in the delivery area!
        '422':
          description: Unprocessable Entity Error
    delete:
      tags:
        - customer
      summary: Deletes a customer
      description: ''
      operationId: customerService.delete
      produces:
        - application/json
      parameters:
        - name: customerId
          in: path
          description: customer id to delete
          required: true
          type: string
      responses:
        '204':
          description: Successful - No Content
        '400':
          description: Invalid Content
        '404':
          description: Customer not found
definitions:
  customer:
    type: object
    properties:
      _id:
        type: string
        description: individual uuid - set by the system
      address:
        type: string
        description: the full address of the customer
      zipCode:
        type: string
        description: zip code that is in the delivery area
      emmailAddress:
        type: string
        description: email addresse of the customer
      firstName:
        type: string
        description: first name of the customer
      lastName:
        type: string
        description: last name of the customer
